
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { WardrobeItem } from './types';

export const defaultWardrobe: WardrobeItem[] = [
  // --- SHIRTS (Products) ---
  { id: 'blue-denim-shirt', name: 'Blue Denim Shirt', url: 'https://mabsuit-479703.web.app/shirts/michael-andrews-blue-denim-shirt.png', type: 'product', category: 'Shirt' },
  { id: 'grey-block-stripe', name: 'Grey Block Stripe', url: 'https://mabsuit-479703.web.app/shirts/michael-andrews-grey-block-stripe-shirt.png', type: 'product', category: 'Shirt' },
  { id: 'black-gingham-spread', name: 'Black Gingham Spread', url: 'https://mabsuit-479703.web.app/shirts/product_black_gingham_spread-collar_shirt.png', type: 'product', category: 'Shirt' },
  { id: 'blue-dot-motif', name: 'Blue Dot Motif', url: 'https://mabsuit-479703.web.app/shirts/product_blue_printed_dot_motif_italian_collar_shirt.png', type: 'product', category: 'Shirt' },
  { id: 'blue-micro-gingham', name: 'Blue Micro Gingham', url: 'https://mabsuit-479703.web.app/shirts/product_blue_textured_micro-gingham_spread-collar_shirt.png', type: 'product', category: 'Shirt' },
  { id: 'brown-gingham', name: 'Brown Gingham', url: 'https://mabsuit-479703.web.app/shirts/product_brown_gingham_spread-collar_shirt.png', type: 'product', category: 'Shirt' },
  { id: 'burgundy-stripe', name: 'Burgundy Stripe', url: 'https://mabsuit-479703.web.app/shirts/product_burgundy_thin_stripe_classic-collar_shirt.png', type: 'product', category: 'Shirt' },
  { id: 'charcoal-tattersall', name: 'Charcoal Tattersall', url: 'https://mabsuit-479703.web.app/shirts/product_charcoal_tattersall_tab-collar_shirt.png', type: 'product', category: 'Shirt' },
  { id: 'ice-grey-stripe-classic', name: 'Ice Grey Stripe', url: 'https://mabsuit-479703.web.app/shirts/product_ice_grey_twill_complex_stripe_classic-collar_shirt.png', type: 'product', category: 'Shirt' },
  { id: 'lavender-houndstooth', name: 'Lavender Houndstooth', url: 'https://mabsuit-479703.web.app/shirts/product_lavender_micro-houndstooth_traditional-collar_shirt.png', type: 'product', category: 'Shirt' },
  { id: 'periwinkle-houndstooth', name: 'Periwinkle Houndstooth', url: 'https://mabsuit-479703.web.app/shirts/product_periwinkle_twill_houndstooth_spread-collar_shirt.png', type: 'product', category: 'Shirt' },
  { id: 'white-tuxedo-wing', name: 'White Tuxedo Wing', url: 'https://mabsuit-479703.web.app/shirts/white_tuxedo_shirt_wing_collar_14.png', type: 'product', category: 'Shirt' },

  // --- SUITS (Products) ---
  { id: 'suit-00002', name: 'Black Two-Button Super 110s', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00002_02386_main_black-two-button-super-110s-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00004', name: 'Medium Grey Pick-Pick Classic', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00004_02395_main_medium-grey-pick-pick-classic-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00005', name: 'Grey Glen Plaid Windowpane', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00005_02390_main_grey-glen-plaid-windowpane-classic-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00008', name: 'Dark Navy Blue Super 110s', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00008_02404_main_dark-navy-blue-super-110s-two-button-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00009', name: 'Charcoal Twill Classic', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00009_02392_main_charcoal-twill-classic-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00013', name: 'Navy Blue Signature', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00013_02407_main_navy-blue-signature-two-button-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00017', name: 'Bordeaux Twill Signature', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00017_02391_main_bordeaux-twill-signature-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00022', name: 'Medium Grey Pick-Pick Signature', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00022_02405_main_medium-grey-pick-pick-signature-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00052', name: 'Charcoal Gun Check Signature', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00052_02401_main_charcoal-gun-check-signature-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00079', name: 'Charcoal Birdseye Classic', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00079_00929_main_charcoal-birdseye-classic-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00080', name: 'Marine Birdseye Classic', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00080_02398_main_marine-birdseye-classic-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00103', name: 'Steel Grey Flannel Classic', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00103_02383_main_steel-grey-flannel-classic-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00110', name: 'Royal Blue Super 150s', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00110_02406_main_royal-blue-super-150s-two-button-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00111', name: 'Navy Blue Solid Super 110s', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00111_02402_main_navy-blue-solid-super-110s-two-button-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00131', name: 'Navy Herringbone Classic', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00131_02408_main_navy-herringbone-classic-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00768', name: 'Khaki Cotton Bespoke', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00768_02379_main_khaki-cotton-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00769', name: 'Light Grey Sharkskin Bespoke', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00769_02375_main_bespoke-light-grey-sharkskin-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00775', name: 'Dark Brown Linen Bespoke', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00775_01954_main_dark-brown-linen-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00776', name: 'Light Grey Pinstripe Bespoke', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00776_02377_light-grey-pinstripe-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-00781', name: 'Cream Plain Weave Bespoke', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00781_01969_main_cream-plain-weave-bespoke-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-01398', name: 'Royal Blue Two-Button MTM', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/01398_02848_main_royal-blue-two-button-wool-mtm-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-01407', name: 'Medium Grey Sharkskin MTM', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/01407_02841_main_medium-grey-sharkskin-two-button-wool-mtm-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-01426', name: 'Medium Blue Wool-Linen MTM', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/01426_02821_main_medium-blue-two-button-wool-linen-blend-mtm-suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-rust-cord', name: 'Rust Corduroy Suit', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/MAB-Rust-Corduroy-Suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-blue-pin', name: 'Blue Pinstripe Suit', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/Michael-Andrews-Blue-Pinstripe-Suit-Large-Square-2-410x470.jpg', type: 'product', category: 'Suit' },
  { id: 'suit-brown-donegal', name: 'Brown Donegal Tweed', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/Michael-Andrews-Custom-Brown-Donegal-Tweed-Suit-Main-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-custom-grey', name: 'Custom Grey Suit', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/Michael-Andrews-Custom-Grey-Suit-410x470.png', type: 'product', category: 'Suit' },
  { id: 'suit-green', name: 'Green Suit', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/Michael-Andrews-Green-Suit-Large-Square-410x470.jpg', type: 'product', category: 'Suit' },
  { id: 'suit-navy-twill-mtm', name: 'Navy Blue Twill MTM', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/Navy-Blue-Twill-Two-Button-Wool-MTM-Suit-410x470.png', type: 'product', category: 'Suit' },

  // --- HOLLAND & SHERRY ---
  { id: 'ESHS-9819600H', name: 'H&S 9819600H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-9819600H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-983503H', name: 'H&S 983503H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-983503H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986001H', name: 'H&S 986001H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986001H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986002H', name: 'H&S 986002H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986002H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986006H', name: 'H&S 986006H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986006H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986007H', name: 'H&S 986007H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986007H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986008H', name: 'H&S 986008H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986008H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986009H', name: 'H&S 986009H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986009H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986010H', name: 'H&S 986010H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986010H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986011H', name: 'H&S 986011H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986011H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986018H', name: 'H&S 986018H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986018H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986024H', name: 'H&S 986024H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986024H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986025H', name: 'H&S 986025H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986025H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986026H', name: 'H&S 986026H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986026H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986027H', name: 'H&S 986027H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986027H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986028H', name: 'H&S 986028H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986028H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986031H', name: 'H&S 986031H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986031H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986032H', name: 'H&S 986032H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986032H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986036H', name: 'H&S 986036H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986036H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986500H', name: 'H&S 986500H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986500H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986501H', name: 'H&S 986501H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986501H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986502H', name: 'H&S 986502H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986502H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986503H', name: 'H&S 986503H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986503H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986504H', name: 'H&S 986504H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986504H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986505H', name: 'H&S 986505H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986505H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986506H', name: 'H&S 986506H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986506H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },
  { id: 'ESHS-986508H', name: 'H&S 986508H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESHS-986508H.jpg', type: 'fabric', category: 'Fabric', mill: 'Holland & Sherry' },

  // --- SCABAL ---
  { id: 'SSCA-852442', name: 'Scabal 852442', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852442Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852443', name: 'Scabal 852443', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852443Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852446', name: 'Scabal 852446', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852446Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852455', name: 'Scabal 852455', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852455Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852457', name: 'Scabal 852457', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852457Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852462', name: 'Scabal 852462', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852462Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852466', name: 'Scabal 852466', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852466Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852467', name: 'Scabal 852467', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852467Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852468', name: 'Scabal 852468', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852468Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852474', name: 'Scabal 852474', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852474Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852482', name: 'Scabal 852482', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852482Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852781', name: 'Scabal 852781', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852781Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852782', name: 'Scabal 852782', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852782Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852783', name: 'Scabal 852783', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852783Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852784', name: 'Scabal 852784', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852784Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852785', name: 'Scabal 852785', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852785Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852786', name: 'Scabal 852786', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852786Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852787', name: 'Scabal 852787', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852787Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852791', name: 'Scabal 852791', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852791Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852793', name: 'Scabal 852793', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852793Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852794', name: 'Scabal 852794', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852794Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852795', name: 'Scabal 852795', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852795Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },
  { id: 'SSCA-852806', name: 'Scabal 852806', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SSCA-852806Scaba.jpg', type: 'fabric', category: 'Fabric', mill: 'Scabal' },

  // --- DORMEUIL ---
  { id: 'ESDM-140005D', name: 'Dormeuil 140005D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-140005D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-140006D', name: 'Dormeuil 140006D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-140006D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-300001D', name: 'Dormeuil 300001D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-300001D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-300002D', name: 'Dormeuil 300002D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-300002D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-300009D', name: 'Dormeuil 300009D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-300009D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-300094D', name: 'Dormeuil 300094D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-300094D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-301486D', name: 'Dormeuil 301486D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-301486D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-470202D', name: 'Dormeuil 470202D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-470202D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-571784D', name: 'Dormeuil 571784D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-571784D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-572997D', name: 'Dormeuil 572997D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-572997D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-796002D', name: 'Dormeuil 796002D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-796002D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-796003D', name: 'Dormeuil 796003D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-796003D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },
  { id: 'ESDM-994120D', name: 'Dormeuil 994120D', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESDM-994120D.jpg', type: 'fabric', category: 'Fabric', mill: 'Dormeuil' },

  // --- LORO PIANA ---
  { id: 'ESLP-N734011L', name: 'LP N734011L', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESLP-N734011L.jpg', type: 'fabric', category: 'Fabric', mill: 'Loro Piana' },
  { id: 'ESLP-N775024L', name: 'LP N775024L', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESLP-N775024L.jpg', type: 'fabric', category: 'Fabric', mill: 'Loro Piana' },
  { id: 'ESLP-N775041L', name: 'LP N775041L', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESLP-N775041L.jpg', type: 'fabric', category: 'Fabric', mill: 'Loro Piana' },

  // --- OTHER MILLS ---
  { id: 'ESAT-2255', name: '2255', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESAT-2255.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESLM-853L', name: '853L', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESLM-853L.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESLW-3502', name: '3502', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESLW-3502.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESLW-6020', name: '6020', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESLW-6020.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESMB-21534W', name: '21534W', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESMB-21534W.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESMB-21567W', name: '21567W', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESMB-21567W.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESMB-21580W', name: '21580W', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESMB-21580W.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESMB-21581W', name: '21581W', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESMB-21581W.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESMB-21582W', name: '21582W', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESMB-21582W.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESMB-21583W', name: '21583W', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESMB-21583W.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESMB-34641W', name: '34641W', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESMB-34641W.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-17025E', name: '17025E', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-17025E.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-17026E', name: '17026E', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-17026E.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-18015S', name: '18015S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-18015S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-18018S', name: '18018S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-18018S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-18022S', name: '18022S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-18022S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-21013S', name: '21013S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-21013S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-21018S', name: '21018S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-21018S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-21024S', name: '21024S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-21024S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-21027S', name: '21027S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-21027S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-28015S', name: '28015S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-28015S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-28016S', name: '28016S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-28016S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-28017S', name: '28017S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-28017S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-28020S', name: '28020S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-28020S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESSD-28040S', name: '28040S', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-28040S.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESTD-F7291T', name: 'F7291T', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESTD-F7291T.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESTD-F7413M', name: 'F7413M', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESTD-F7413M.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'ESTR-TRA004F', name: 'TRA004F', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESTR-TRA004F.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'HSWC-11556', name: '11556', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/HSWC-11556.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'HSWC-61275', name: '61275', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/HSWC-61275.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'HSWC-61298', name: '61298', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/HSWC-61298.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'HSWC-62349', name: '62349', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/HSWC-62349.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SBAC-KUSHKA', name: 'KUSHKA', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SBAC-KUSHKA.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SBAC-MARIKA', name: 'MARIKA', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SBAC-MARIKA.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SBAC-NIKEL', name: 'NIKEL', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SBAC-NIKEL.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SBMC-BK301_BE439', name: 'BK301_BE439', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SBMC-BK301_BE439.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SBMC-CW001', name: 'CW001', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SBMC-CW001.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SBMC-NY322_BE439', name: 'NY322_BE439', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SBMC-NY322_BE439.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SCYC-CYC', name: 'CYC', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SCYC-CYC.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SHFW-0222H', name: '0222H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SHFW-0222H.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SHFW-2003J', name: '2003J', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SHFW-2003J.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SHFW-2016J', name: '2016J', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SHFW-2016J.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SHFW-2021J', name: '2021J', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SHFW-2021J.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SHFW-904889H', name: '904889H', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SHFW-904889H.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'SMAB-T', name: 'SMAB-T', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SMAB-T.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
  { id: 'STAC-O', name: 'STAC-O', url: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/STAC-O.jpg', type: 'fabric', category: 'Fabric', mill: 'Other Mills' },
];
