import type { ShirtData } from '../types';

// ============================================================================
// MICHAEL ANDREWS BESPOKE - SHIRT CATALOG
// Complete bespoke and made-to-measure dress shirt collection
// ============================================================================

export const SHIRTS: ShirtData[] = [
    // ============================================================================
    // DRESS SHIRTS - Classic Business
    // ============================================================================
    {
        id: 'white-royal-oxford',
        name: 'White Royal Oxford Dress Shirt',
        category: 'Dress Shirts',
        description: 'The quintessential business shirt. Crisp white Royal Oxford cloth with subtle texture.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SHFW-0222H.jpg',
        promptDescription: 'Professional white oxford cloth dress shirt. Crisp, clean white fabric with characteristic oxford weave texture. Perfect for business settings.',
        baseColor: 'White',
        colorHex: '#FFFFFF',
        pattern: 'Oxford Weave',
        fabricType: 'Royal Oxford Cotton',
        fabricMill: 'Premium Import',
        weight: '100s 2-ply',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/white-royal-oxford-shirt/',
        compatibleFabricIds: ['SHFW-0222H', 'SBMC-CW001'],
    },
    {
        id: 'light-blue-poplin',
        name: 'Light Blue Poplin Dress Shirt',
        category: 'Dress Shirts',
        description: 'Classic light blue in smooth poplin. The perfect complement to navy and grey suits.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SHFW-2021J.jpg',
        promptDescription: 'Light blue poplin dress shirt. Smooth, crisp fabric in soft sky blue. Classic business elegance.',
        baseColor: 'Light Blue',
        colorHex: '#ADD8E6',
        pattern: 'Solid',
        fabricType: 'Poplin Cotton',
        fabricMill: 'Premium Import',
        weight: '100s 2-ply',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/light-blue-poplin-shirt/',
        compatibleFabricIds: ['SHFW-2021J', 'ESSD-28015S', 'ESSD-28016S'],
    },
    {
        id: 'white-herringbone',
        name: 'White Herringbone Dress Shirt',
        category: 'Dress Shirts',
        description: 'Elegant white with subtle herringbone texture. Adds depth and visual interest.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SHFW-904889H.jpg',
        promptDescription: 'White herringbone pattern dress shirt. Elegant texture with diagonal weave pattern visible up close. Sophisticated business attire.',
        baseColor: 'White',
        colorHex: '#FAFAFA',
        pattern: 'Herringbone',
        fabricType: 'Herringbone Cotton',
        fabricMill: 'Premium Import',
        weight: '120s 2-ply',
        price: '$325',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Cutaway',
        cuffStyle: 'French',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/white-herringbone-shirt/',
        compatibleFabricIds: ['SHFW-904889H'],
    },
    {
        id: 'blue-twill',
        name: 'French Blue Twill Dress Shirt',
        category: 'Dress Shirts',
        description: 'Rich French blue in smooth twill weave. Deeper than standard light blue.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SHFW-2016J.jpg',
        promptDescription: 'French blue twill dress shirt. Deeper blue shade with diagonal twill weave. Professional and distinctive.',
        baseColor: 'French Blue',
        colorHex: '#0072BB',
        pattern: 'Twill',
        fabricType: 'Twill Cotton',
        fabricMill: 'Premium Import',
        weight: '100s 2-ply',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/french-blue-twill-shirt/',
        compatibleFabricIds: ['SHFW-2016J', 'SHFW-2003J'],
    },

    // ============================================================================
    // FORMAL SHIRTS - For Special Occasions
    // ============================================================================
    {
        id: 'white-formal-pique',
        name: 'White Formal Piqué Dress Shirt',
        category: 'Formal',
        description: 'Traditional formal shirt with marcella piqué bib front. For black tie occasions.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SBMC-CW001.jpg',
        promptDescription: 'White formal piqué dress shirt with marcella bib front. Wing collar, French cuffs. Black tie formal wear.',
        baseColor: 'White',
        colorHex: '#FFFFFF',
        pattern: 'Piqué Bib',
        fabricType: 'Marcella Cotton',
        fabricMill: 'Premium Import',
        weight: '140s 2-ply',
        price: '$395',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Wing',
        cuffStyle: 'French',
        frontStyle: 'Piqué Bib',
        productUrl: 'https://www.michaelandrews.com/product/white-formal-pique-shirt/',
    },
    {
        id: 'white-formal-plain',
        name: 'White Formal Broadcloth Shirt',
        category: 'Formal',
        description: 'Crisp white broadcloth for formal occasions. Versatile for business or events.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SBMC-CW001.jpg',
        promptDescription: 'White broadcloth formal dress shirt. Ultra-smooth finish, wing or spread collar options. Elegant formal attire.',
        baseColor: 'White',
        colorHex: '#FFFFFF',
        pattern: 'Solid',
        fabricType: 'Broadcloth Cotton',
        fabricMill: 'Premium Import',
        weight: '120s 2-ply',
        price: '$345',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'French',
        frontStyle: 'Fly Front',
        productUrl: 'https://www.michaelandrews.com/product/white-formal-broadcloth-shirt/',
    },

    // ============================================================================
    // BUSINESS CASUAL - Refined but Relaxed
    // ============================================================================
    {
        id: 'chambray-blue',
        name: 'Chambray Blue Casual Shirt',
        category: 'Business Casual',
        description: 'Soft chambray in medium blue. Perfect for business casual Fridays.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-28040S.jpg',
        promptDescription: 'Medium blue chambray shirt. Soft, casual texture with denim-like appearance. Business casual style.',
        baseColor: 'Medium Blue',
        colorHex: '#6495ED',
        pattern: 'Chambray',
        fabricType: 'Chambray Cotton',
        fabricMill: 'Premium Import',
        weight: '4oz',
        price: '$275',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Button-Down',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/chambray-blue-shirt/',
    },
    {
        id: 'ecru-linen',
        name: 'Ecru Linen Casual Shirt',
        category: 'Business Casual',
        description: 'Natural ecru linen for warm weather. Breathable with relaxed elegance.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-21027S.jpg',
        promptDescription: 'Ecru natural linen shirt. Light, breathable fabric with characteristic linen texture. Summer casual elegance.',
        baseColor: 'Ecru',
        colorHex: '#F5F5DC',
        pattern: 'Solid',
        fabricType: 'Pure Linen',
        fabricMill: 'Premium Import',
        weight: '4oz',
        price: '$315',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Camp',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/ecru-linen-shirt/',
    },
    {
        id: 'pink-gingham',
        name: 'Pink Gingham Check Shirt',
        category: 'Business Casual',
        description: 'Classic pink gingham with subtle check pattern. Adds color to casual looks.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-18015S.jpg',
        promptDescription: 'Pink gingham check shirt. Small check pattern in soft pink and white. Smart casual style.',
        baseColor: 'Pink',
        colorHex: '#FFB6C1',
        pattern: 'Gingham Check',
        fabricType: 'Poplin Cotton',
        fabricMill: 'Premium Import',
        weight: '100s 2-ply',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Button-Down',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/pink-gingham-shirt/',
    },

    // ============================================================================
    // SPORT SHIRTS - Weekend & Leisure
    // ============================================================================
    {
        id: 'navy-bengal-stripe',
        name: 'Navy Bengal Stripe Sport Shirt',
        category: 'Sport',
        description: 'Bold navy and white Bengal stripes. Statement piece for casual settings.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SBMC-NY322_BE439.jpg',
        promptDescription: 'Navy and white Bengal stripe shirt. Bold vertical stripes. Casual sport shirt style.',
        baseColor: 'Navy/White',
        colorHex: '#000080',
        pattern: 'Bengal Stripe',
        fabricType: 'Poplin Cotton',
        fabricMill: 'Premium Import',
        weight: '100s',
        price: '$285',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/navy-bengal-stripe-shirt/',
    },
    {
        id: 'tan-brushed-twill',
        name: 'Tan Brushed Twill Sport Shirt',
        category: 'Sport',
        description: 'Soft brushed twill in warm tan. Perfect for fall and winter casual.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-21013S.jpg',
        promptDescription: 'Tan brushed twill sport shirt. Soft, warm fabric in earthy tan color. Fall/winter casual style.',
        baseColor: 'Tan',
        colorHex: '#D2B48C',
        pattern: 'Brushed Twill',
        fabricType: 'Brushed Cotton Twill',
        fabricMill: 'Premium Import',
        weight: '5oz',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Button-Down',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/tan-brushed-twill-shirt/',
    },

    // ============================================================================
    // MADE-TO-MEASURE OPTIONS - More Accessible Price Point
    // ============================================================================
    {
        id: 'mtm-white-poplin',
        name: 'White Poplin MTM Dress Shirt',
        category: 'Dress Shirts',
        description: 'Essential white poplin at an accessible price. Made-to-measure fit.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SBMC-CW001.jpg',
        promptDescription: 'White poplin dress shirt. Clean, crisp finish. Professional business attire.',
        baseColor: 'White',
        colorHex: '#FFFFFF',
        pattern: 'Solid',
        fabricType: 'Poplin Cotton',
        fabricMill: 'Premium Import',
        weight: '80s 2-ply',
        price: '$175',
        productionTime: '3-4 weeks',
        productionType: 'Made-to-Measure',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/mtm-white-poplin-shirt/',
    },
    {
        id: 'mtm-blue-poplin',
        name: 'Light Blue Poplin MTM Dress Shirt',
        category: 'Dress Shirts',
        description: 'Classic light blue at an accessible price. Made-to-measure fit.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/SHFW-2021J.jpg',
        promptDescription: 'Light blue poplin dress shirt. Smooth finish in soft blue. Professional but approachable.',
        baseColor: 'Light Blue',
        colorHex: '#ADD8E6',
        pattern: 'Solid',
        fabricType: 'Poplin Cotton',
        fabricMill: 'Premium Import',
        weight: '80s 2-ply',
        price: '$175',
        productionTime: '3-4 weeks',
        productionType: 'Made-to-Measure',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/mtm-blue-poplin-shirt/',
    },
    {
        id: 'mtm-blue-stripe',
        name: 'Blue Stripe MTM Dress Shirt',
        category: 'Dress Shirts',
        description: 'Timeless blue and white stripes at an accessible price.',
        imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/fabric_swatches/ESSD-28020S.jpg',
        promptDescription: 'Blue and white stripe dress shirt. Classic banker stripes. Professional business style.',
        baseColor: 'Blue/White',
        colorHex: '#4169E1',
        pattern: 'Stripe',
        fabricType: 'Poplin Cotton',
        fabricMill: 'Premium Import',
        weight: '80s 2-ply',
        price: '$185',
        productionTime: '3-4 weeks',
        productionType: 'Made-to-Measure',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: 'https://www.michaelandrews.com/product/mtm-blue-stripe-shirt/',
    },
    // ============================================================================
    // NEW ARRIVALS - Full Product Shots
    // ============================================================================
    {
        id: 'blue-denim-shirt',
        name: 'Blue Denim Shirt',
        category: 'Business Casual',
        description: 'Casual blue denim shirt. Perfect for a relaxed yet polished look.',
        imageUrl: '/shirts/michael-andrews-blue-denim-shirt.png',
        promptDescription: 'Blue denim dress shirt. Soft, washed denim texture. Casual elegance.',
        baseColor: 'Blue',
        colorHex: '#4682B4',
        pattern: 'Solid',
        fabricType: 'Denim',
        fabricMill: 'Imported',
        weight: '6oz',
        price: '$275',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'grey-block-stripe',
        name: 'Grey Block Stripe Shirt',
        category: 'Dress Shirts',
        description: 'Bold grey block stripes on white. assertive and modern.',
        imageUrl: '/shirts/michael-andrews-grey-block-stripe-shirt.png',
        promptDescription: 'Grey and white block stripe dress shirt. Wide vertical stripes. Professional statement.',
        baseColor: 'Grey/White',
        colorHex: '#808080',
        pattern: 'Block Stripe',
        fabricType: 'Poplin',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'black-gingham-spread',
        name: 'Black Gingham Spread Collar Shirt',
        category: 'Business Casual',
        description: 'Sharp black and white gingham check. versatile for day or night.',
        imageUrl: '/shirts/product_black_gingham_spread-collar_shirt.png',
        promptDescription: 'Black and white gingham check shirt. Small check pattern. Modern casual style.',
        baseColor: 'Black/White',
        colorHex: '#000000',
        pattern: 'Gingham',
        fabricType: 'Poplin',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'blue-dot-motif',
        name: 'Blue Dot Motif Shirt',
        category: 'Business Casual',
        description: 'Subtle blue dot motif. Adds texture and interest close up.',
        imageUrl: '/shirts/product_blue_printed_dot_motif_italian_collar_shirt.png',
        promptDescription: 'Blue dress shirt with small printed dot motif. Micro-pattern adds texture. Italian collar.',
        baseColor: 'Blue',
        colorHex: '#4169E1',
        pattern: 'Dot Motif',
        fabricType: 'Printed Cotton',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Italian',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'blue-micro-gingham',
        name: 'Blue Micro-Gingham Shirt',
        category: 'Business Casual',
        description: 'Classic blue micro-gingham. A wardrobe staple.',
        imageUrl: '/shirts/product_blue_textured_micro-gingham_spread-collar_shirt.png',
        promptDescription: 'Blue and white micro-gingham check shirt. Very small check pattern appears textured from distance.',
        baseColor: 'Blue/White',
        colorHex: '#87CEEB',
        pattern: 'Micro Gingham',
        fabricType: 'Poplin',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'brown-gingham',
        name: 'Brown Gingham Shirt',
        category: 'Business Casual',
        description: 'Warm brown gingham check. Great for fall layering.',
        imageUrl: '/shirts/product_brown_gingham_spread-collar_shirt.png',
        promptDescription: 'Brown and white gingham check shirt. Classic check pattern in earth tones.',
        baseColor: 'Brown/White',
        colorHex: '#8B4513',
        pattern: 'Gingham',
        fabricType: 'Poplin',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'burgundy-stripe',
        name: 'Burgundy Thin Stripe Shirt',
        category: 'Dress Shirts',
        description: 'Sophisticated burgundy stripes. A distinctive business option.',
        imageUrl: '/shirts/product_burgundy_thin_stripe_classic-collar_shirt.png',
        promptDescription: 'White dress shirt with thin burgundy vertical stripes. Classic collar. Professional look.',
        baseColor: 'White/Burgundy',
        colorHex: '#800020',
        pattern: 'Stripe',
        fabricType: 'Poplin',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Classic',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'charcoal-tattersall',
        name: 'Charcoal Tattersall Shirt',
        category: 'Business Casual',
        description: 'Classic charcoal tattersall check. Refined country style.',
        imageUrl: '/shirts/product_charcoal_tattersall_tab-collar_shirt.png',
        promptDescription: 'Charcoal and white tattersall check shirt. Grid pattern. Tab collar detail.',
        baseColor: 'White/Charcoal',
        colorHex: '#36454F',
        pattern: 'Tattersall',
        fabricType: 'Poplin',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Tab',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'ice-grey-stripe-classic',
        name: 'Ice Grey Complex Stripe Shirt',
        category: 'Dress Shirts',
        description: 'Intricate ice grey stripes. Modern and sharp.',
        imageUrl: '/shirts/product_ice_grey_twill_complex_stripe_classic-collar_shirt.png',
        promptDescription: 'Ice grey and white complex stripe shirt. Twill weave. Classic collar.',
        baseColor: 'Ice Grey',
        colorHex: '#D3D3D3',
        pattern: 'Complex Stripe',
        fabricType: 'Twill',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$315',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Classic',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'lavender-houndstooth',
        name: 'Lavender Micro-Houndstooth Shirt',
        category: 'Dress Shirts',
        description: 'Subtle lavender houndstooth. Adds color without being loud.',
        imageUrl: '/shirts/product_lavender_micro-houndstooth_traditional-collar_shirt.png',
        promptDescription: 'Lavender and white micro-houndstooth pattern shirt. Traditional collar. Soft purple hue.',
        baseColor: 'Lavender',
        colorHex: '#E6E6FA',
        pattern: 'Houndstooth',
        fabricType: 'Poplin',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Traditional',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'light-blue-poplin-classic',
        name: 'Light Blue Poplin Classic Shirt',
        category: 'Dress Shirts',
        description: 'The standard light blue poplin. Classic collar.',
        imageUrl: '/shirts/product_light_blue_poplin_classic-collar_shirt.png',
        promptDescription: 'Light blue solid poplin dress shirt. Classic collar. Business essential.',
        baseColor: 'Light Blue',
        colorHex: '#ADD8E6',
        pattern: 'Solid',
        fabricType: 'Poplin',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Classic',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'pale-pink-gingham',
        name: 'Pale Pink Micro-Gingham Shirt',
        category: 'Business Casual',
        description: 'Soft pale pink micro-gingham. Summer ready.',
        imageUrl: '/shirts/product_pale_pink_micro-gingham_spread-collar_shirt.png',
        promptDescription: 'Pale pink and white micro-gingham check shirt. Spread collar. Soft and approachable.',
        baseColor: 'Pale Pink',
        colorHex: '#FFB6C1',
        pattern: 'Micro Gingham',
        fabricType: 'Poplin',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'periwinkle-houndstooth',
        name: 'Periwinkle Houndstooth Shirt',
        category: 'Dress Shirts',
        description: 'Vibrant periwinkle in a houndstooth weave.',
        imageUrl: '/shirts/product_periwinkle_twill_houndstooth_spread-collar_shirt.png',
        promptDescription: 'Periwinkle blue houndstooth pattern shirt. Twill weave. Spread collar.',
        baseColor: 'Periwinkle',
        colorHex: '#CCCCFF',
        pattern: 'Houndstooth',
        fabricType: 'Twill',
        fabricMill: 'Imported',
        weight: '100s',
        price: '$295',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Spread',
        cuffStyle: 'Barrel',
        frontStyle: 'Placket',
        productUrl: '#',
    },
    {
        id: 'white-tuxedo-wing',
        name: 'White Tuxedo Wing Collar Shirt',
        category: 'Formal',
        description: 'Classic white tuxedo shirt with wing collar.',
        imageUrl: '/shirts/white_tuxedo_shirt_wing_collar_14.png',
        promptDescription: 'White formal tuxedo shirt. Wing collar. For black tie events.',
        baseColor: 'White',
        colorHex: '#FFFFFF',
        pattern: 'Solid',
        fabricType: 'Poplin',
        fabricMill: 'Imported',
        weight: '120s',
        price: '$345',
        productionTime: '4-6 weeks',
        productionType: 'Bespoke',
        collarStyle: 'Wing',
        cuffStyle: 'French',
        frontStyle: 'Fly Front',
        productUrl: '#',
    },
];

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

export const getShirtsByCategory = (category: ShirtData['category']): ShirtData[] => {
    return SHIRTS.filter(s => s.category === category);
};

export const getShirtsByProductionType = (type: 'Bespoke' | 'Made-to-Measure'): ShirtData[] => {
    return SHIRTS.filter(s => s.productionType === type);
};

export const getAllShirtCategories = (): ShirtData['category'][] => {
    return ['Dress Shirts', 'Business Casual', 'Formal', 'Sport'];
};
