import type { SuitData } from './types';

// Production suit catalog from CSV
export const SUITS: SuitData[] = [
  {
    id: 'charcoal-grey-db-pinstripe',
    name: 'Charcoal Grey Double Breasted Pinstripe Suit',
    category: 'Greys',
    description: 'Classic two-button pinstriped suit in charcoal grey',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/Michael-Andrews-Custom-Grey-Suit-410x470.png',
    promptDescription: 'Professional studio photography, man wearing a charcoal grey pinstripe suit. Double-breasted with 6 buttons, classic notch lapels. The wool fabric shows sharp vertical pinstripes. Paired with white dress shirt and classic tie. Professional business setting.',
    color: 'Charcoal Grey',
    colorHex: '#2C3E50',
    pattern: 'Pinstripe',
    fabricType: 'Wool',
    fabricMill: 'Premium Import',
    weight: '130z',
    price: '$3,595',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 6,
    lapelStyle: 'Double-Breasted Notch',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/grey-and-off-white-striped-suit/',
  },
  {
    id: 'medium-brown-donegal-tweed',
    name: 'Medium Brown Donegal Tweed Suit',
    category: 'Browns',
    description: 'Textured brown Donegal tweed suit',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/Michael-Andrews-Custom-Brown-Donegal-Tweed-Suit-Main-410x470.png',
    promptDescription: 'Professional photography, man in medium brown Donegal tweed suit. Textured wool tweed with characteristic colorful flecks. Two-button, notch lapels, classic shoulders. Rustic yet refined. Country gentleman aesthetic.',
    color: 'Medium Brown',
    colorHex: '#8B6F47',
    pattern: 'Donegal Tweed',
    fabricType: 'Wool Tweed',
    fabricMill: 'Premium Import',
    weight: '140z',
    price: '$3,295',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/medium-brown-donegal-tweed-suit/',
  },
  {
    id: 'black-solid-twill',
    name: 'Black Solid Twill Bespoke Suit',
    category: 'Specialty',
    description: 'Fine worsted black suit with smooth twill finish',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00002_02386_main_black-two-button-super-110s-bespoke-suit-410x470.png',
    promptDescription: 'Professional studio photography, man in black Super 110s wool suit. Solid twill weave with smooth finish. Two-button, notch lapels, contemporary shoulders. Fine worsted fabric with subtle sheen. Formal business attire.',
    color: 'Black',
    colorHex: '#000000',
    pattern: 'Solid Twill',
    fabricType: 'Super 110s Wool',
    fabricMill: 'Premium Import',
    weight: '110z',
    price: '$3,495',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Contemporary',
    productUrl: 'https://www.michaelandrews.com/product/black-two-button-super-110s-bespoke-suit/',
  },
  {
    id: 'steel-grey-flannel',
    name: 'Steel Grey Flannel Bespoke Suit',
    category: 'Greys',
    description: 'Soft brushed wool flannel in steel grey',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00103_02383_main_steel-grey-flannel-classic-bespoke-suit-410x470.png',
    promptDescription: 'Professional photography, man in steel grey flannel suit. Soft brushed wool with matte finish. Two-button, notch lapels, classic shoulders. The flannel fabric shows soft texture and warmth. Fall/winter sophistication.',
    color: 'Steel Grey',
    colorHex: '#4A5568',
    pattern: 'Solid Flannel',
    fabricType: 'Wool Flannel',
    fabricMill: 'Premium Import',
    weight: '140z',
    price: '$4,295',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/steel-grey-flannel-classic-bespoke-suit/',
  },
  {
    id: 'grey-sharkskin',
    name: 'Grey Sharkskin Bespoke Suit',
    category: 'Greys',
    description: 'Subtle pick-and-pick pattern for dimensional texture',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00004_02395_main_medium-grey-pick-pick-classic-bespoke-suit-410x470.png',
    promptDescription: 'Professional studio photography, man in grey sharkskin suit. Tight weave pick-and-pick pattern creating subtle shimmer. Two-button, notch lapels, classic shoulders. Dimensional texture from weave. Business professional.',
    color: 'Grey',
    colorHex: '#7F8C8D',
    pattern: 'Sharkskin',
    fabricType: 'Wool Sharkskin',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$3,995',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/medium-grey-pick-pick-classic-bespoke-suit/',
  },
  {
    id: 'rust-brown-corduroy',
    name: 'Rust Brown Cotton/Wool Stretch Corduroy Suit',
    category: 'Browns',
    description: 'Textured corduroy with comfort stretch',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/MAB-Rust-Corduroy-Suit-410x470.png',
    promptDescription: 'Professional photography, man in rust brown corduroy suit. Cotton/wool stretch corduroy with raised pile texture. Two-button, notch lapels, contemporary shoulders. Vertical ribs visible, warm reddish-brown color. Casual elegance.',
    color: 'Rust Brown',
    colorHex: '#A0522D',
    pattern: 'Corduroy',
    fabricType: 'Cotton/Wool Stretch Corduroy',
    fabricMill: 'Premium Blend',
    weight: '150z',
    price: '$4,095',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Contemporary',
    productUrl: 'https://www.michaelandrews.com/product/rust-cotton-wool-stretch-corduroy-suit/',
  },
  {
    id: 'dark-navy-super-110s',
    name: "Dark Navy Blue Super 110's Bespoke Suit",
    category: 'Navy Blues',
    description: 'Fine two-ply worsted dark navy suit',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00008_02404_main_dark-navy-blue-super-110s-two-button-bespoke-suit-410x470.png',
    promptDescription: 'Professional studio photography, man in dark navy Super 110s suit. Fine worsted wool, nearly black navy. Two-button, notch lapels, classic shoulders. Smooth finish with subtle sheen. Ultimate professional power suit.',
    color: 'Dark Navy',
    colorHex: '#001F3F',
    pattern: 'Solid',
    fabricType: 'Super 110s Wool',
    fabricMill: 'Premium Import',
    weight: '110z',
    price: '$3,495',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/dark-navy-blue-super-110s-two-button-bespoke-suit/',
  },
  {
    id: 'navy-blue-solid',
    name: 'Navy Blue Solid Bespoke Suit',
    category: 'Navy Blues',
    description: 'Classic navy worsted suit',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00111_02402_main_navy-blue-solid-super-110s-two-button-bespoke-suit-410x470.png',
    promptDescription: 'Professional photography, man in classic navy blue Super 110s suit. Solid worsted wool, two-button, notch lapels, classic shoulders. Versatile navy blue, fine wool texture. Signature business suit.',
    color: 'Navy Blue',
    colorHex: '#003D7A',
    pattern: 'Solid',
    fabricType: 'Super 110s Wool',
    fabricMill: 'Premium Import',
    weight: '110z',
    price: '$3,495',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/navy-blue-solid-super-110s-two-button-bespoke-suit/',
  },
  {
    id: 'cream-plain-weave',
    name: 'Cream Plain Weave Bespoke Suit',
    category: 'Specialty',
    description: 'Lightweight cream suit, perfect for spring/summer',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00781_01969_main_cream-plain-weave-bespoke-suit-410x470.png',
    promptDescription: 'Professional photography, man in cream plain weave suit. Light ivory wool, two-button, notch lapels, contemporary shoulders. Airy lightweight fabric. Summer wedding or garden party aesthetic.',
    color: 'Cream',
    colorHex: '#FFF8DC',
    pattern: 'Plain Weave',
    fabricType: 'Wool Plain Weave',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$3,895',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Contemporary',
    productUrl: 'https://www.michaelandrews.com/product/cream-plain-weave-bespoke-suit/',
  },
  {
    id: 'navy-blue-signature',
    name: 'Navy Blue Signature Two-button Bespoke Suit',
    category: 'Navy Blues',
    description: 'Exclusive MAB signature cut navy suit',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00013_02407_main_navy-blue-signature-two-button-bespoke-suit-410x470.png',
    promptDescription: 'Professional studio photography, man in navy signature weave suit. Exclusive MAB cut with signature shoulders. Two-button, notch lapels. Navy wool with distinct weave. Executive confidence.',
    color: 'Navy Blue',
    colorHex: '#1F4788',
    pattern: 'Signature Weave',
    fabricType: 'Wool Signature Weave',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$3,995',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Signature',
    productUrl: 'https://www.michaelandrews.com/product/navy-blue-signature-two-button-bespoke-suit/',
  },
  {
    id: 'charcoal-gun-check',
    name: 'Charcoal Gun Check Signature Bespoke Suit',
    category: 'Greys',
    description: 'Classic gun check pattern suit',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00052_02401_main_charcoal-gun-check-signature-bespoke-suit-410x470.png',
    promptDescription: 'Professional photography, man in charcoal gun check suit. Classic check pattern in charcoal wool. Two-button, notch lapels, signature shoulders. Subtle pattern with traditional appeal.',
    color: 'Charcoal',
    colorHex: '#36454F',
    pattern: 'Gun Check',
    fabricType: 'Wool Gun Check',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$3,595',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Signature',
    productUrl: 'https://www.michaelandrews.com/product/charcoal-gun-check-signature-bespoke-suit/',
  },
  {
    id: 'dark-brown-linen',
    name: 'Dark Brown Linen Bespoke Suit',
    category: 'Browns',
    description: 'Lightweight breathable linen for warm weather',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00775_01954_main_dark-brown-linen-bespoke-suit-410x470.png',
    promptDescription: 'Professional photography, man in dark brown linen suit. Lightweight wool-linen blend with natural texture. Two-button, notch lapels, classic shoulders. Breathable summer fabric with characteristic wrinkles.',
    color: 'Dark Brown',
    colorHex: '#654321',
    pattern: 'Solid Linen',
    fabricType: 'Wool Linen',
    fabricMill: 'Premium Import',
    weight: '110z',
    price: '$4,495',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/dark-brown-linen-bespoke-suit/',
  },
  {
    id: 'khaki-cotton',
    name: 'Khaki Cotton Bespoke Suit',
    category: 'Browns',
    description: 'Casual cotton khaki suit',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00768_02379_main_khaki-cotton-bespoke-suit-410x470.png',
    promptDescription: 'Professional photography, man in khaki cotton suit. Light tan cotton fabric, two-button, notch lapels, contemporary shoulders. Casual elegance, summer suit for garden parties.',
    color: 'Khaki',
    colorHex: '#F0E68C',
    pattern: 'Solid Cotton',
    fabricType: 'Cotton',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$3,195',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Contemporary',
    productUrl: 'https://www.michaelandrews.com/product/khaki-cotton-bespoke-suit/',
  },
  {
    id: 'light-grey-sharkskin',
    name: 'Light Grey Sharkskin Bespoke Suit',
    category: 'Greys',
    description: 'Subtle dimensional texture',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00769_02375_main_bespoke-light-grey-sharkskin-bespoke-suit-410x470.png',
    promptDescription: 'Professional studio photography, man in light grey sharkskin suit. Pick-and-pick weave creating subtle shimmer. Two-button, notch lapels, contemporary shoulders. Light grey color, dimensional texture.',
    color: 'Light Grey',
    colorHex: '#D3D3D3',
    pattern: 'Sharkskin',
    fabricType: 'Wool Sharkskin',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$3,895',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Contemporary',
    productUrl: 'https://www.michaelandrews.com/product/bespoke-light-grey-sharkskin-bespoke-suit/',
  },
  {
    id: 'mid-grey-sharkskin',
    name: 'Mid-Grey Sharkskin Bespoke Suit',
    category: 'Greys',
    description: 'Pick and pick weave detailing',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00022_02405_main_medium-grey-pick-pick-signature-bespoke-suit-410x470.png',
    promptDescription: 'Professional photography, man in mid-grey sharkskin suit. Pick-and-pick pattern with signature shoulders. Two-button, notch lapels. Refined grey tone with weave texture.',
    color: 'Mid-Grey',
    colorHex: '#A9A9A9',
    pattern: 'Sharkskin',
    fabricType: 'Wool Sharkskin',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$3,995',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Signature',
    productUrl: 'https://www.michaelandrews.com/product/medium-grey-pick-pick-signature-bespoke-suit/',
  },
  {
    id: 'hunter-green-seersucker',
    name: 'Hunter Green Wool Seersucker Suit',
    category: 'Specialty',
    description: 'Seasonal green seersucker',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/Michael-Andrews-Green-Suit-Large-Square-410x470.jpg',
    promptDescription: 'Professional photography, man in hunter green seersucker suit. Wool seersucker with puckered texture. Two-button, notch lapels, contemporary shoulders. Seasonal summer fabric in rich green.',
    color: 'Hunter Green',
    colorHex: '#355E3B',
    pattern: 'Seersucker',
    fabricType: 'Wool Seersucker',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$3,795',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Contemporary',
    productUrl: 'https://www.michaelandrews.com/product/green-seersucker-suit/',
  },
  {
    id: 'navy-herringbone',
    name: 'Navy Herringbone Classic Bespoke Suit',
    category: 'Navy Blues',
    description: 'Classic herringbone weave',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00131_02408_main_navy-herringbone-classic-bespoke-suit-410x470.png',
    promptDescription: 'Professional studio photography, man in navy herringbone suit. Diagonal herringbone weave pattern. Two-button, notch lapels, classic shoulders. Navy wool with visible texture.',
    color: 'Navy',
    colorHex: '#0047AB',
    pattern: 'Herringbone',
    fabricType: 'Wool Herringbone',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$3,495',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/navy-herringbone-classic-bespoke-suit/',
  },
  {
    id: 'medium-blue-wool-linen-mtm',
    name: 'Medium Blue Wool-Linen MTM Suit',
    category: 'Made-to-Measure',
    description: 'Breathable blend MTM option',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/01426_02821_main_medium-blue-two-button-wool-linen-blend-mtm-suit-410x470.png',
    promptDescription: 'Professional photography, man in medium blue wool-linen blend suit. Made-to-measure, breathable blend fabric. Two-button, notch lapels, classic shoulders. Vibrant medium blue, summer weight.',
    color: 'Medium Blue',
    colorHex: '#4169E1',
    pattern: 'Wool-Linen Blend',
    fabricType: 'Wool-Linen Blend',
    fabricMill: 'Premium Blend',
    weight: '110z',
    price: '$1,595',
    productionTime: '6-8 weeks',
    productionType: 'Made-to-Measure',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/medium-blue-two-button-wool-linen-blend-mtm-suit/',
  },
  {
    id: 'royal-blue-150s',
    name: "Royal Blue 150's Bespoke Suit",
    category: 'Royal Blues',
    description: 'Ultra-fine Super 150s fabric',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00110_02406_main_royal-blue-super-150s-two-button-bespoke-suit-410x470.png',
    promptDescription: 'Professional studio photography, man in royal blue Super 150s suit. Ultra-fine worsted wool, vibrant royal blue. Two-button, notch lapels, classic shoulders. Luxurious drape and sheen.',
    color: 'Royal Blue',
    colorHex: '#4169E1',
    pattern: 'Solid',
    fabricType: 'Super 150s Wool',
    fabricMill: 'Premium Import',
    weight: '110z',
    price: '$4,495',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/royal-blue-super-150s-two-button-bespoke-suit/',
  },
  {
    id: 'royal-blue-mtm',
    name: 'Royal Blue MTM Suit',
    category: 'Made-to-Measure',
    description: 'Royal blue MTM option',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/01398_02848_main_royal-blue-two-button-wool-mtm-suit-410x470.png',
    promptDescription: 'Professional photography, man in royal blue MTM suit. Made-to-measure, vibrant royal blue wool. Two-button, notch lapels, classic shoulders. Affordable luxury option.',
    color: 'Royal Blue',
    colorHex: '#4169E1',
    pattern: 'Solid',
    fabricType: 'Wool',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$1,695',
    productionTime: '6-8 weeks',
    productionType: 'Made-to-Measure',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/royal-blue-two-button-wool-mtm-suit/',
  },
  {
    id: 'grey-sharkskin-mtm',
    name: 'Grey Sharkskin MTM Suit',
    category: 'Made-to-Measure',
    description: 'Grey MTM sharkskin',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/01407_02841_main_medium-grey-sharkskin-two-button-wool-mtm-suit-410x470.png',
    promptDescription: 'Professional photography, man in grey sharkskin MTM suit. Made-to-measure, pick-and-pick weave. Two-button, notch lapels, classic shoulders. Affordable sharkskin option.',
    color: 'Grey',
    colorHex: '#808080',
    pattern: 'Sharkskin',
    fabricType: 'Wool Sharkskin',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$1,495',
    productionTime: '6-8 weeks',
    productionType: 'Made-to-Measure',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/medium-grey-sharkskin-two-button-wool-mtm-suit/',
  },
  {
    id: 'navy-blue-twill-mtm',
    name: 'Navy Blue Twill MTM Suit',
    category: 'Made-to-Measure',
    description: 'Navy MTM twill option',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/Navy-Blue-Twill-Two-Button-Wool-MTM-Suit-410x470.png',
    promptDescription: 'Professional photography, man in navy twill MTM suit. Made-to-measure, diagonal twill weave. Two-button, notch lapels, classic shoulders. Classic navy business suit.',
    color: 'Navy',
    colorHex: '#000080',
    pattern: 'Twill',
    fabricType: 'Wool Twill',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$1,695',
    productionTime: '6-8 weeks',
    productionType: 'Made-to-Measure',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/navy-blue-twill-two-button-wool-mtm-suit/',
  },
  {
    id: 'charcoal-twill-classic',
    name: 'Charcoal Twill Classic Bespoke Suit',
    category: 'Greys',
    description: 'Heavy-weight twill construction',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00009_02392_main_charcoal-twill-classic-bespoke-suit-410x470.png',
    promptDescription: 'Professional studio photography, man in charcoal twill suit. Heavy-weight wool twill with diagonal ribs. Two-button, notch lapels, classic shoulders. Substantial feel, ideal for winter.',
    color: 'Charcoal',
    colorHex: '#36454F',
    pattern: 'Twill',
    fabricType: 'Wool Twill',
    fabricMill: 'Premium Import',
    weight: '130z',
    price: '$4,495',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/charcoal-twill-classic-bespoke-suit/',
  },
  {
    id: 'aubergine-twill',
    name: 'Aubergine Twill Signature Bespoke Suit',
    category: 'Specialty',
    description: 'Deep aubergine with signature cut',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00017_02391_main_bordeaux-twill-signature-bespoke-suit-410x470.png',
    promptDescription: 'Professional photography, man in aubergine/bordeaux twill suit. Deep burgundy-purple wool twill. Two-button, notch lapels, signature shoulders. Bold statement suit.',
    color: 'Aubergine',
    colorHex: '#800020',
    pattern: 'Twill',
    fabricType: 'Wool Twill',
    fabricMill: 'Premium Import',
    weight: '130z',
    price: '$4,295',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Signature',
    productUrl: 'https://www.michaelandrews.com/product/bordeaux-twill-signature-bespoke-suit/',
  },
  {
    id: 'charcoal-birdseye',
    name: 'Charcoal Birdseye Classic Bespoke Suit',
    category: 'Greys',
    description: 'Classic birdseye pattern',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00079_00929_main_charcoal-birdseye-classic-bespoke-suit-410x470.png',
    promptDescription: 'Professional studio photography, man in charcoal birdseye suit. Small diamond birdseye pattern. Two-button, notch lapels, classic shoulders. Subtle texture, refined finish.',
    color: 'Charcoal',
    colorHex: '#36454F',
    pattern: 'Birdseye',
    fabricType: 'Wool Birdseye',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$4,095',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/charcoal-birdseye-classic-bespoke-suit/',
  },
  {
    id: 'marine-birdseye',
    name: 'Marine Birdseye Classic Bespoke Suit',
    category: 'Navy Blues',
    description: 'Marine blue birdseye weave',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00080_02398_main_marine-birdseye-classic-bespoke-suit-410x470.png',
    promptDescription: 'Professional photography, man in marine blue birdseye suit. Bright marine blue with small diamond pattern. Two-button, notch lapels, classic shoulders. Vibrant yet professional.',
    color: 'Marine',
    colorHex: '#1E90FF',
    pattern: 'Birdseye',
    fabricType: 'Wool Birdseye',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$4,095',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/marine-birdseye-classic-bespoke-suit/',
  },
  {
    id: 'light-grey-pinstripe',
    name: 'Light Grey Pinstripe Bespoke Suit',
    category: 'Greys',
    description: 'Classic light grey pinstripe',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00776_02377_light-grey-pinstripe-bespoke-suit-410x470.png',
    promptDescription: 'Professional studio photography, man in light grey pinstripe suit. Vertical pin stripes on light grey wool. Two-button, notch lapels, classic shoulders. Elegant daytime formal suit.',
    color: 'Light Grey',
    colorHex: '#D3D3D3',
    pattern: 'Pinstripe',
    fabricType: 'Wool Pinstripe',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$4,095',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/light-grey-pinstripe-bespoke-suit/',
  },
  {
    id: 'grey-glen-plaid-windowpane',
    name: 'Grey Glen Plaid Windowpane Bespoke Suit',
    category: 'Greys',
    description: 'Sophisticated plaid pattern',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/00005_02390_main_grey-glen-plaid-windowpane-classic-bespoke-suit-410x470.png',
    promptDescription: 'Professional photography, man in grey glen plaid windowpane suit. Glen plaid pattern with windowpane overlay. Two-button, notch lapels, classic shoulders. Complex pattern, executive style.',
    color: 'Grey',
    colorHex: '#808080',
    pattern: 'Glen Plaid Windowpane',
    fabricType: 'Wool Glen Plaid',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$4,195',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Classic',
    productUrl: 'https://www.michaelandrews.com/product/grey-glen-plaid-windowpane-classic-bespoke-suit/',
  },
  {
    id: 'denim-blue-chalk-stripe',
    name: 'Denim Blue Chalk Stripe Suit with Silk Knots',
    category: 'Royal Blues',
    description: 'Unique chalk stripe pattern',
    imageUrl: 'https://storage.googleapis.com/mabbucket/MABSUITapp/suits/Michael-Andrews-Blue-Pinstripe-Suit-Large-Square-2-410x470.jpg',
    promptDescription: 'Professional photography, man in denim blue chalk stripe suit. Bold white chalk stripes on denim blue wool. Two-button, notch lapels, contemporary shoulders. Statement business suit with silk knot details.',
    color: 'Denim Blue',
    colorHex: '#1F75FE',
    pattern: 'Chalk Stripe',
    fabricType: 'Wool Chalk Stripe',
    fabricMill: 'Premium Import',
    weight: '120z',
    price: '$3,995',
    productionTime: '10-12 weeks',
    productionType: 'Bespoke',
    buttonCount: 2,
    lapelStyle: 'Notch Lapel',
    shoulderCut: 'Contemporary',
    productUrl: 'https://www.michaelandrews.com/product/denim-blue-chalk-stripe-suit-with-silk-knots/',
  },
];
